# Generated by Django 6.0.6 on 2026-06-15 11:14

import webapp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_remove_task_type_task_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, default='', validators=[webapp.validators.validate_no_placeholder], verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='summary',
            field=models.CharField(max_length=200, validators=[webapp.validators.validate_summary_capital], verbose_name='Краткое описание'),
        ),
    ]
