# Generated by Django 6.0.6 on 2026-07-02 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_project_task_project'),
    ]

    operations = [
    ]
